#!/bin/bash

# This script acts like a continuous integration client for informant board.
# The latest code is pulled from
# Directions:
#   Run this script normally and the latest code will be synced in ./informant/
#   To set as startup on raspberry pi: run_ci --install

LOCALDIR=`pwd`
GITDIR=$LOCALDIR/informant/

# Set as startup program on raspberry pi
function install {
    exit
}

# Remove as startup program on raspberry pi
function uninstall {
    exit
}

function start_informant {
    exit
}

function stop_informant {
    kill informant.py
}

function init_git {
    if [ -d $GITDIR ]; then
        return
    fi
    #mkdir $GITDIR
    #if [ ! -d $GITDIR ]; then
    #    echo "Error: Could not make dir '$(GITDIR)'"
    #    exit 1
    #fi
    #cd $GITDIR
    git clone https://github.com/youresam/informant.git
    #cd $LOCALDIR
}

function query_git {
    cd $GITDIR
    [ "`git log --pretty=%H ...refs/heads/master^ | head -n 1`" = "`git ls-remote origin -h refs/heads/master |cut -f1`" ] && changed=0 || changed=1
    cd $LOCALDIR
    echo "changed? "
    echo $changed
}

init_git

query_git

exit 0


start_informant

while true; do

done